More comprehensive CI

diff --git a/.github/workflows/gh-pages.yml b/.github/workflows/gh-pages.yml
--- a/.github/workflows/gh-pages.yml
+++ b/.github/workflows/gh-pages.yml
@@ -13,15 +13,42 @@ env:
 
 jobs:
   # ------------------------------------------------------------------
+  # Check if marian submodule was updated
+  # ------------------------------------------------------------------
+check_source:
+    name: Check for source changes
+    runs-on: ubuntu-latest
+    outputs:
+      changed: ${{ steps.check.outputs.changed }}
+    steps:
+      - name: Checkout source code
+        uses: actions/checkout@v2
+
+      - name: Determine changes since last event
+        id: check
+        env:
+          ref: ${{ github.event.before }}
+        run: |
+          if [ -z "${{ env.ref }}" ]; then
+            echo '::set-output name=changed::true';
+          else
+            git fetch origin ${{ env.ref }} --depth=1
+            git diff --name-only ${{ env.ref }}.. | grep '^marian-dev' && \
+              echo '::set-output name=changed::true' || true
+          fi
+
+  # ------------------------------------------------------------------
   # Compile Marian to get CLI options
   # ------------------------------------------------------------------
   cli:
     runs-on: ubuntu-latest
+    needs: [check_source]
+    if: needs.check_source.outputs.changed == 'true'
     defaults:
       run:
         working-directory: marian-dev
     steps:
-      - name: Checkout website source
+      - name: Checkout source code
         uses: actions/checkout@v2
         with:
           submodules: true
@@ -99,11 +126,12 @@ jobs:
           path: ~/marian-dev/build/cli
 
   # ------------------------------------------------------------------
-  # Build Jekyll source
+  # Build website source
   # ------------------------------------------------------------------
-  jekyll:
+  site:
     runs-on: ubuntu-latest
-    if: ${{ false }} # disabled for now
+    needs: [cli]
+    if: ${{ !failure() }}  # skipped needs are fine, but failures are not
     steps:
       - name: Checkout website source
         uses: actions/checkout@v2
@@ -130,9 +158,10 @@ jobs:
           path: ./_site
 
 # Generates API docs
-  api-documentation:
+  api:
     runs-on: ubuntu-latest
-    if: ${{ false }} # disabled for now
+    needs: [check_source]
+    if: needs.check_source.outputs.changed == 'true'
     defaults:
       run:
         working-directory: marian-dev
@@ -174,22 +203,14 @@ jobs:
           name: api-docs-output
           path: ./marian-dev/doc/build/html
 
-# # Compiles Marian and ingests CLI options
-#     cli:
-#       runs-on: ubuntu-latest
-#       steps:
-#         - name: Checkout website source
-#           uses: actions/checkout@v2
-#           with:
-#             submodules: recursive
-#         - run: ls -valpsh marian-dev
 
-# # Deploy to branch
-#     deploy:
-#       # needs: [jekyll, docs, cli]
-#       runs-on: ubuntu-latest
-#       steps:
-#         - run: git push
+# Deploy to branch
+    deploy:
+      needs: [site, api, cli]
+      if: ${{ !failure() }}  # skipped needs are fine, but failures are not
+      runs-on: ubuntu-latest
+      steps:
+        - run: echo 'Good to go!'
 
 
       # - name: Install
